
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Operator: 'Operator',
  Vessel: 'Vessel',
  Trip: 'Trip',
  TripSchedule: 'TripSchedule',
  PriceTier: 'PriceTier',
  TripSeat: 'TripSeat',
  Booking: 'Booking',
  BookingItem: 'BookingItem',
  Payment: 'Payment',
  WebhookEvent: 'WebhookEvent',
  Manifest: 'Manifest',
  Passenger: 'Passenger',
  Checkin: 'Checkin',
  SeatLock: 'SeatLock',
  AuditLog: 'AuditLog',
  EmailLog: 'EmailLog',
  Review: 'Review',
  PromoCode: 'PromoCode'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  phone: 'phone',
  fullName: 'fullName',
  role: 'role',
  profilePictureUrl: 'profilePictureUrl',
  isActive: 'isActive',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const OperatorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationName: 'organizationName',
  companyName: 'companyName',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  verified: 'verified',
  rating: 'rating',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type OperatorScalarFieldEnum = (typeof OperatorScalarFieldEnum)[keyof typeof OperatorScalarFieldEnum]


export const VesselScalarFieldEnum = {
  id: 'id',
  operatorId: 'operatorId',
  name: 'name',
  registrationNo: 'registrationNo',
  capacity: 'capacity',
  description: 'description',
  vesselMetadata: 'vesselMetadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type VesselScalarFieldEnum = (typeof VesselScalarFieldEnum)[keyof typeof VesselScalarFieldEnum]


export const TripScalarFieldEnum = {
  id: 'id',
  vesselId: 'vesselId',
  operatorId: 'operatorId',
  title: 'title',
  description: 'description',
  category: 'category',
  externalReference: 'externalReference',
  durationMinutes: 'durationMinutes',
  isRecurring: 'isRecurring',
  amenities: 'amenities',
  highlights: 'highlights',
  departurePort: 'departurePort',
  arrivalPort: 'arrivalPort',
  routeName: 'routeName',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
} as const

export type TripScalarFieldEnum = (typeof TripScalarFieldEnum)[keyof typeof TripScalarFieldEnum]


export const TripScheduleScalarFieldEnum = {
  id: 'id',
  tripId: 'tripId',
  startTime: 'startTime',
  endTime: 'endTime',
  capacity: 'capacity',
  bookedSeats: 'bookedSeats',
  status: 'status',
  departurePort: 'departurePort',
  arrivalPort: 'arrivalPort',
  baseCurrency: 'baseCurrency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TripScheduleScalarFieldEnum = (typeof TripScheduleScalarFieldEnum)[keyof typeof TripScheduleScalarFieldEnum]


export const PriceTierScalarFieldEnum = {
  id: 'id',
  tripScheduleId: 'tripScheduleId',
  name: 'name',
  description: 'description',
  amountKobo: 'amountKobo',
  priceKobo: 'priceKobo',
  capacity: 'capacity',
  position: 'position',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PriceTierScalarFieldEnum = (typeof PriceTierScalarFieldEnum)[keyof typeof PriceTierScalarFieldEnum]


export const TripSeatScalarFieldEnum = {
  id: 'id',
  tripScheduleId: 'tripScheduleId',
  seatLabel: 'seatLabel',
  tierId: 'tierId',
  isActive: 'isActive',
  createdAt: 'createdAt'
} as const

export type TripSeatScalarFieldEnum = (typeof TripSeatScalarFieldEnum)[keyof typeof TripSeatScalarFieldEnum]


export const BookingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tripScheduleId: 'tripScheduleId',
  operatorId: 'operatorId',
  priceTierId: 'priceTierId',
  status: 'status',
  paymentStatus: 'paymentStatus',
  bookingReference: 'bookingReference',
  numberOfPassengers: 'numberOfPassengers',
  totalAmountKobo: 'totalAmountKobo',
  currency: 'currency',
  holdExpiresAt: 'holdExpiresAt',
  promoCode: 'promoCode',
  discountKobo: 'discountKobo',
  qrCode: 'qrCode',
  confirmedAt: 'confirmedAt',
  failureReason: 'failureReason',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  cancelledAt: 'cancelledAt'
} as const

export type BookingScalarFieldEnum = (typeof BookingScalarFieldEnum)[keyof typeof BookingScalarFieldEnum]


export const BookingItemScalarFieldEnum = {
  id: 'id',
  bookingId: 'bookingId',
  priceTierId: 'priceTierId',
  tripSeatId: 'tripSeatId',
  passengerName: 'passengerName',
  passengerPhone: 'passengerPhone',
  ticketReference: 'ticketReference',
  status: 'status',
  createdAt: 'createdAt'
} as const

export type BookingItemScalarFieldEnum = (typeof BookingItemScalarFieldEnum)[keyof typeof BookingItemScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  bookingId: 'bookingId',
  provider: 'provider',
  providerPaymentId: 'providerPaymentId',
  status: 'status',
  amountKobo: 'amountKobo',
  currency: 'currency',
  rawResponse: 'rawResponse',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const WebhookEventScalarFieldEnum = {
  id: 'id',
  provider: 'provider',
  eventType: 'eventType',
  providerEventId: 'providerEventId',
  payload: 'payload',
  signature: 'signature',
  receivedAt: 'receivedAt',
  processed: 'processed',
  processedAt: 'processedAt',
  processingError: 'processingError'
} as const

export type WebhookEventScalarFieldEnum = (typeof WebhookEventScalarFieldEnum)[keyof typeof WebhookEventScalarFieldEnum]


export const ManifestScalarFieldEnum = {
  id: 'id',
  tripScheduleId: 'tripScheduleId',
  generatedById: 'generatedById',
  generatedAt: 'generatedAt',
  payload: 'payload'
} as const

export type ManifestScalarFieldEnum = (typeof ManifestScalarFieldEnum)[keyof typeof ManifestScalarFieldEnum]


export const PassengerScalarFieldEnum = {
  id: 'id',
  bookingId: 'bookingId',
  priceTierId: 'priceTierId',
  fullName: 'fullName',
  phone: 'phone',
  email: 'email',
  emergencyContact: 'emergencyContact',
  specialNeeds: 'specialNeeds',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PassengerScalarFieldEnum = (typeof PassengerScalarFieldEnum)[keyof typeof PassengerScalarFieldEnum]


export const CheckinScalarFieldEnum = {
  id: 'id',
  bookingItemId: 'bookingItemId',
  bookingId: 'bookingId',
  passengerId: 'passengerId',
  checkedInById: 'checkedInById',
  checkedInAt: 'checkedInAt',
  method: 'method'
} as const

export type CheckinScalarFieldEnum = (typeof CheckinScalarFieldEnum)[keyof typeof CheckinScalarFieldEnum]


export const SeatLockScalarFieldEnum = {
  id: 'id',
  tripScheduleId: 'tripScheduleId',
  tripSeatId: 'tripSeatId',
  bookingId: 'bookingId',
  lockedById: 'lockedById',
  lockedAt: 'lockedAt',
  expiresAt: 'expiresAt'
} as const

export type SeatLockScalarFieldEnum = (typeof SeatLockScalarFieldEnum)[keyof typeof SeatLockScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  action: 'action',
  userId: 'userId',
  changes: 'changes',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const EmailLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  recipient: 'recipient',
  channel: 'channel',
  type: 'type',
  subject: 'subject',
  body: 'body',
  metadata: 'metadata',
  provider: 'provider',
  providerMsgId: 'providerMsgId',
  status: 'status',
  errorMessage: 'errorMessage',
  sentAt: 'sentAt',
  createdAt: 'createdAt'
} as const

export type EmailLogScalarFieldEnum = (typeof EmailLogScalarFieldEnum)[keyof typeof EmailLogScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  tripId: 'tripId',
  userId: 'userId',
  rating: 'rating',
  title: 'title',
  comment: 'comment',
  isVerified: 'isVerified',
  isPublic: 'isPublic',
  adminResponse: 'adminResponse',
  respondedAt: 'respondedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const PromoCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  description: 'description',
  discountType: 'discountType',
  discountValue: 'discountValue',
  priceTierId: 'priceTierId',
  minPurchase: 'minPurchase',
  maxDiscount: 'maxDiscount',
  usageLimit: 'usageLimit',
  usageCount: 'usageCount',
  perUserLimit: 'perUserLimit',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PromoCodeScalarFieldEnum = (typeof PromoCodeScalarFieldEnum)[keyof typeof PromoCodeScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

