
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BookingItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BookingItem
 * 
 */
export type BookingItemModel = runtime.Types.Result.DefaultSelection<Prisma.$BookingItemPayload>

export type AggregateBookingItem = {
  _count: BookingItemCountAggregateOutputType | null
  _min: BookingItemMinAggregateOutputType | null
  _max: BookingItemMaxAggregateOutputType | null
}

export type BookingItemMinAggregateOutputType = {
  id: string | null
  bookingId: string | null
  priceTierId: string | null
  tripSeatId: string | null
  passengerName: string | null
  passengerPhone: string | null
  passengerEmail: string | null
  ticketReference: string | null
  status: $Enums.CheckinStatus | null
  createdAt: Date | null
}

export type BookingItemMaxAggregateOutputType = {
  id: string | null
  bookingId: string | null
  priceTierId: string | null
  tripSeatId: string | null
  passengerName: string | null
  passengerPhone: string | null
  passengerEmail: string | null
  ticketReference: string | null
  status: $Enums.CheckinStatus | null
  createdAt: Date | null
}

export type BookingItemCountAggregateOutputType = {
  id: number
  bookingId: number
  priceTierId: number
  tripSeatId: number
  passengerName: number
  passengerPhone: number
  passengerEmail: number
  ticketReference: number
  status: number
  createdAt: number
  _all: number
}


export type BookingItemMinAggregateInputType = {
  id?: true
  bookingId?: true
  priceTierId?: true
  tripSeatId?: true
  passengerName?: true
  passengerPhone?: true
  passengerEmail?: true
  ticketReference?: true
  status?: true
  createdAt?: true
}

export type BookingItemMaxAggregateInputType = {
  id?: true
  bookingId?: true
  priceTierId?: true
  tripSeatId?: true
  passengerName?: true
  passengerPhone?: true
  passengerEmail?: true
  ticketReference?: true
  status?: true
  createdAt?: true
}

export type BookingItemCountAggregateInputType = {
  id?: true
  bookingId?: true
  priceTierId?: true
  tripSeatId?: true
  passengerName?: true
  passengerPhone?: true
  passengerEmail?: true
  ticketReference?: true
  status?: true
  createdAt?: true
  _all?: true
}

export type BookingItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BookingItem to aggregate.
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookingItems to fetch.
   */
  orderBy?: Prisma.BookingItemOrderByWithRelationInput | Prisma.BookingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BookingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BookingItems
  **/
  _count?: true | BookingItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BookingItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BookingItemMaxAggregateInputType
}

export type GetBookingItemAggregateType<T extends BookingItemAggregateArgs> = {
      [P in keyof T & keyof AggregateBookingItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBookingItem[P]>
    : Prisma.GetScalarType<T[P], AggregateBookingItem[P]>
}




export type BookingItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingItemWhereInput
  orderBy?: Prisma.BookingItemOrderByWithAggregationInput | Prisma.BookingItemOrderByWithAggregationInput[]
  by: Prisma.BookingItemScalarFieldEnum[] | Prisma.BookingItemScalarFieldEnum
  having?: Prisma.BookingItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BookingItemCountAggregateInputType | true
  _min?: BookingItemMinAggregateInputType
  _max?: BookingItemMaxAggregateInputType
}

export type BookingItemGroupByOutputType = {
  id: string
  bookingId: string
  priceTierId: string | null
  tripSeatId: string | null
  passengerName: string | null
  passengerPhone: string | null
  passengerEmail: string | null
  ticketReference: string | null
  status: $Enums.CheckinStatus
  createdAt: Date
  _count: BookingItemCountAggregateOutputType | null
  _min: BookingItemMinAggregateOutputType | null
  _max: BookingItemMaxAggregateOutputType | null
}

type GetBookingItemGroupByPayload<T extends BookingItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BookingItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BookingItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BookingItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BookingItemGroupByOutputType[P]>
      }
    >
  >



export type BookingItemWhereInput = {
  AND?: Prisma.BookingItemWhereInput | Prisma.BookingItemWhereInput[]
  OR?: Prisma.BookingItemWhereInput[]
  NOT?: Prisma.BookingItemWhereInput | Prisma.BookingItemWhereInput[]
  id?: Prisma.StringFilter<"BookingItem"> | string
  bookingId?: Prisma.StringFilter<"BookingItem"> | string
  priceTierId?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  tripSeatId?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerName?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerPhone?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerEmail?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  ticketReference?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  status?: Prisma.EnumCheckinStatusFilter<"BookingItem"> | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFilter<"BookingItem"> | Date | string
  booking?: Prisma.XOR<Prisma.BookingScalarRelationFilter, Prisma.BookingWhereInput>
  priceTier?: Prisma.XOR<Prisma.PriceTierNullableScalarRelationFilter, Prisma.PriceTierWhereInput> | null
  tripSeat?: Prisma.XOR<Prisma.TripSeatNullableScalarRelationFilter, Prisma.TripSeatWhereInput> | null
  checkin?: Prisma.XOR<Prisma.CheckinNullableScalarRelationFilter, Prisma.CheckinWhereInput> | null
}

export type BookingItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrderInput | Prisma.SortOrder
  tripSeatId?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerName?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  ticketReference?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  booking?: Prisma.BookingOrderByWithRelationInput
  priceTier?: Prisma.PriceTierOrderByWithRelationInput
  tripSeat?: Prisma.TripSeatOrderByWithRelationInput
  checkin?: Prisma.CheckinOrderByWithRelationInput
}

export type BookingItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tripSeatId?: string
  AND?: Prisma.BookingItemWhereInput | Prisma.BookingItemWhereInput[]
  OR?: Prisma.BookingItemWhereInput[]
  NOT?: Prisma.BookingItemWhereInput | Prisma.BookingItemWhereInput[]
  bookingId?: Prisma.StringFilter<"BookingItem"> | string
  priceTierId?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerName?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerPhone?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerEmail?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  ticketReference?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  status?: Prisma.EnumCheckinStatusFilter<"BookingItem"> | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFilter<"BookingItem"> | Date | string
  booking?: Prisma.XOR<Prisma.BookingScalarRelationFilter, Prisma.BookingWhereInput>
  priceTier?: Prisma.XOR<Prisma.PriceTierNullableScalarRelationFilter, Prisma.PriceTierWhereInput> | null
  tripSeat?: Prisma.XOR<Prisma.TripSeatNullableScalarRelationFilter, Prisma.TripSeatWhereInput> | null
  checkin?: Prisma.XOR<Prisma.CheckinNullableScalarRelationFilter, Prisma.CheckinWhereInput> | null
}, "id" | "tripSeatId">

export type BookingItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrderInput | Prisma.SortOrder
  tripSeatId?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerName?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  passengerEmail?: Prisma.SortOrderInput | Prisma.SortOrder
  ticketReference?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.BookingItemCountOrderByAggregateInput
  _max?: Prisma.BookingItemMaxOrderByAggregateInput
  _min?: Prisma.BookingItemMinOrderByAggregateInput
}

export type BookingItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.BookingItemScalarWhereWithAggregatesInput | Prisma.BookingItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.BookingItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BookingItemScalarWhereWithAggregatesInput | Prisma.BookingItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BookingItem"> | string
  bookingId?: Prisma.StringWithAggregatesFilter<"BookingItem"> | string
  priceTierId?: Prisma.StringNullableWithAggregatesFilter<"BookingItem"> | string | null
  tripSeatId?: Prisma.StringNullableWithAggregatesFilter<"BookingItem"> | string | null
  passengerName?: Prisma.StringNullableWithAggregatesFilter<"BookingItem"> | string | null
  passengerPhone?: Prisma.StringNullableWithAggregatesFilter<"BookingItem"> | string | null
  passengerEmail?: Prisma.StringNullableWithAggregatesFilter<"BookingItem"> | string | null
  ticketReference?: Prisma.StringNullableWithAggregatesFilter<"BookingItem"> | string | null
  status?: Prisma.EnumCheckinStatusWithAggregatesFilter<"BookingItem"> | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BookingItem"> | Date | string
}

export type BookingItemCreateInput = {
  id?: string
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  booking: Prisma.BookingCreateNestedOneWithoutItemsInput
  priceTier?: Prisma.PriceTierCreateNestedOneWithoutBookingItemsInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutBookingItemInput
  checkin?: Prisma.CheckinCreateNestedOneWithoutBookingItemInput
}

export type BookingItemUncheckedCreateInput = {
  id?: string
  bookingId: string
  priceTierId?: string | null
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  checkin?: Prisma.CheckinUncheckedCreateNestedOneWithoutBookingItemInput
}

export type BookingItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateOneRequiredWithoutItemsNestedInput
  priceTier?: Prisma.PriceTierUpdateOneWithoutBookingItemsNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutBookingItemNestedInput
  checkin?: Prisma.CheckinUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  checkin?: Prisma.CheckinUncheckedUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemCreateManyInput = {
  id?: string
  bookingId: string
  priceTierId?: string | null
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
}

export type BookingItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BookingItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BookingItemListRelationFilter = {
  every?: Prisma.BookingItemWhereInput
  some?: Prisma.BookingItemWhereInput
  none?: Prisma.BookingItemWhereInput
}

export type BookingItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BookingItemNullableScalarRelationFilter = {
  is?: Prisma.BookingItemWhereInput | null
  isNot?: Prisma.BookingItemWhereInput | null
}

export type BookingItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrder
  passengerName?: Prisma.SortOrder
  passengerPhone?: Prisma.SortOrder
  passengerEmail?: Prisma.SortOrder
  ticketReference?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BookingItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrder
  passengerName?: Prisma.SortOrder
  passengerPhone?: Prisma.SortOrder
  passengerEmail?: Prisma.SortOrder
  ticketReference?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BookingItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  priceTierId?: Prisma.SortOrder
  tripSeatId?: Prisma.SortOrder
  passengerName?: Prisma.SortOrder
  passengerPhone?: Prisma.SortOrder
  passengerEmail?: Prisma.SortOrder
  ticketReference?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type BookingItemCreateNestedManyWithoutPriceTierInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutPriceTierInput, Prisma.BookingItemUncheckedCreateWithoutPriceTierInput> | Prisma.BookingItemCreateWithoutPriceTierInput[] | Prisma.BookingItemUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutPriceTierInput | Prisma.BookingItemCreateOrConnectWithoutPriceTierInput[]
  createMany?: Prisma.BookingItemCreateManyPriceTierInputEnvelope
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
}

export type BookingItemUncheckedCreateNestedManyWithoutPriceTierInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutPriceTierInput, Prisma.BookingItemUncheckedCreateWithoutPriceTierInput> | Prisma.BookingItemCreateWithoutPriceTierInput[] | Prisma.BookingItemUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutPriceTierInput | Prisma.BookingItemCreateOrConnectWithoutPriceTierInput[]
  createMany?: Prisma.BookingItemCreateManyPriceTierInputEnvelope
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
}

export type BookingItemUpdateManyWithoutPriceTierNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutPriceTierInput, Prisma.BookingItemUncheckedCreateWithoutPriceTierInput> | Prisma.BookingItemCreateWithoutPriceTierInput[] | Prisma.BookingItemUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutPriceTierInput | Prisma.BookingItemCreateOrConnectWithoutPriceTierInput[]
  upsert?: Prisma.BookingItemUpsertWithWhereUniqueWithoutPriceTierInput | Prisma.BookingItemUpsertWithWhereUniqueWithoutPriceTierInput[]
  createMany?: Prisma.BookingItemCreateManyPriceTierInputEnvelope
  set?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  disconnect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  delete?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  update?: Prisma.BookingItemUpdateWithWhereUniqueWithoutPriceTierInput | Prisma.BookingItemUpdateWithWhereUniqueWithoutPriceTierInput[]
  updateMany?: Prisma.BookingItemUpdateManyWithWhereWithoutPriceTierInput | Prisma.BookingItemUpdateManyWithWhereWithoutPriceTierInput[]
  deleteMany?: Prisma.BookingItemScalarWhereInput | Prisma.BookingItemScalarWhereInput[]
}

export type BookingItemUncheckedUpdateManyWithoutPriceTierNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutPriceTierInput, Prisma.BookingItemUncheckedCreateWithoutPriceTierInput> | Prisma.BookingItemCreateWithoutPriceTierInput[] | Prisma.BookingItemUncheckedCreateWithoutPriceTierInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutPriceTierInput | Prisma.BookingItemCreateOrConnectWithoutPriceTierInput[]
  upsert?: Prisma.BookingItemUpsertWithWhereUniqueWithoutPriceTierInput | Prisma.BookingItemUpsertWithWhereUniqueWithoutPriceTierInput[]
  createMany?: Prisma.BookingItemCreateManyPriceTierInputEnvelope
  set?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  disconnect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  delete?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  update?: Prisma.BookingItemUpdateWithWhereUniqueWithoutPriceTierInput | Prisma.BookingItemUpdateWithWhereUniqueWithoutPriceTierInput[]
  updateMany?: Prisma.BookingItemUpdateManyWithWhereWithoutPriceTierInput | Prisma.BookingItemUpdateManyWithWhereWithoutPriceTierInput[]
  deleteMany?: Prisma.BookingItemScalarWhereInput | Prisma.BookingItemScalarWhereInput[]
}

export type BookingItemCreateNestedOneWithoutTripSeatInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutTripSeatInput, Prisma.BookingItemUncheckedCreateWithoutTripSeatInput>
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutTripSeatInput
  connect?: Prisma.BookingItemWhereUniqueInput
}

export type BookingItemUncheckedCreateNestedOneWithoutTripSeatInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutTripSeatInput, Prisma.BookingItemUncheckedCreateWithoutTripSeatInput>
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutTripSeatInput
  connect?: Prisma.BookingItemWhereUniqueInput
}

export type BookingItemUpdateOneWithoutTripSeatNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutTripSeatInput, Prisma.BookingItemUncheckedCreateWithoutTripSeatInput>
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutTripSeatInput
  upsert?: Prisma.BookingItemUpsertWithoutTripSeatInput
  disconnect?: Prisma.BookingItemWhereInput | boolean
  delete?: Prisma.BookingItemWhereInput | boolean
  connect?: Prisma.BookingItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BookingItemUpdateToOneWithWhereWithoutTripSeatInput, Prisma.BookingItemUpdateWithoutTripSeatInput>, Prisma.BookingItemUncheckedUpdateWithoutTripSeatInput>
}

export type BookingItemUncheckedUpdateOneWithoutTripSeatNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutTripSeatInput, Prisma.BookingItemUncheckedCreateWithoutTripSeatInput>
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutTripSeatInput
  upsert?: Prisma.BookingItemUpsertWithoutTripSeatInput
  disconnect?: Prisma.BookingItemWhereInput | boolean
  delete?: Prisma.BookingItemWhereInput | boolean
  connect?: Prisma.BookingItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BookingItemUpdateToOneWithWhereWithoutTripSeatInput, Prisma.BookingItemUpdateWithoutTripSeatInput>, Prisma.BookingItemUncheckedUpdateWithoutTripSeatInput>
}

export type BookingItemCreateNestedManyWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutBookingInput, Prisma.BookingItemUncheckedCreateWithoutBookingInput> | Prisma.BookingItemCreateWithoutBookingInput[] | Prisma.BookingItemUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutBookingInput | Prisma.BookingItemCreateOrConnectWithoutBookingInput[]
  createMany?: Prisma.BookingItemCreateManyBookingInputEnvelope
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
}

export type BookingItemUncheckedCreateNestedManyWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutBookingInput, Prisma.BookingItemUncheckedCreateWithoutBookingInput> | Prisma.BookingItemCreateWithoutBookingInput[] | Prisma.BookingItemUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutBookingInput | Prisma.BookingItemCreateOrConnectWithoutBookingInput[]
  createMany?: Prisma.BookingItemCreateManyBookingInputEnvelope
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
}

export type BookingItemUpdateManyWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutBookingInput, Prisma.BookingItemUncheckedCreateWithoutBookingInput> | Prisma.BookingItemCreateWithoutBookingInput[] | Prisma.BookingItemUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutBookingInput | Prisma.BookingItemCreateOrConnectWithoutBookingInput[]
  upsert?: Prisma.BookingItemUpsertWithWhereUniqueWithoutBookingInput | Prisma.BookingItemUpsertWithWhereUniqueWithoutBookingInput[]
  createMany?: Prisma.BookingItemCreateManyBookingInputEnvelope
  set?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  disconnect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  delete?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  update?: Prisma.BookingItemUpdateWithWhereUniqueWithoutBookingInput | Prisma.BookingItemUpdateWithWhereUniqueWithoutBookingInput[]
  updateMany?: Prisma.BookingItemUpdateManyWithWhereWithoutBookingInput | Prisma.BookingItemUpdateManyWithWhereWithoutBookingInput[]
  deleteMany?: Prisma.BookingItemScalarWhereInput | Prisma.BookingItemScalarWhereInput[]
}

export type BookingItemUncheckedUpdateManyWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutBookingInput, Prisma.BookingItemUncheckedCreateWithoutBookingInput> | Prisma.BookingItemCreateWithoutBookingInput[] | Prisma.BookingItemUncheckedCreateWithoutBookingInput[]
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutBookingInput | Prisma.BookingItemCreateOrConnectWithoutBookingInput[]
  upsert?: Prisma.BookingItemUpsertWithWhereUniqueWithoutBookingInput | Prisma.BookingItemUpsertWithWhereUniqueWithoutBookingInput[]
  createMany?: Prisma.BookingItemCreateManyBookingInputEnvelope
  set?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  disconnect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  delete?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  connect?: Prisma.BookingItemWhereUniqueInput | Prisma.BookingItemWhereUniqueInput[]
  update?: Prisma.BookingItemUpdateWithWhereUniqueWithoutBookingInput | Prisma.BookingItemUpdateWithWhereUniqueWithoutBookingInput[]
  updateMany?: Prisma.BookingItemUpdateManyWithWhereWithoutBookingInput | Prisma.BookingItemUpdateManyWithWhereWithoutBookingInput[]
  deleteMany?: Prisma.BookingItemScalarWhereInput | Prisma.BookingItemScalarWhereInput[]
}

export type EnumCheckinStatusFieldUpdateOperationsInput = {
  set?: $Enums.CheckinStatus
}

export type BookingItemCreateNestedOneWithoutCheckinInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutCheckinInput, Prisma.BookingItemUncheckedCreateWithoutCheckinInput>
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutCheckinInput
  connect?: Prisma.BookingItemWhereUniqueInput
}

export type BookingItemUpdateOneWithoutCheckinNestedInput = {
  create?: Prisma.XOR<Prisma.BookingItemCreateWithoutCheckinInput, Prisma.BookingItemUncheckedCreateWithoutCheckinInput>
  connectOrCreate?: Prisma.BookingItemCreateOrConnectWithoutCheckinInput
  upsert?: Prisma.BookingItemUpsertWithoutCheckinInput
  disconnect?: Prisma.BookingItemWhereInput | boolean
  delete?: Prisma.BookingItemWhereInput | boolean
  connect?: Prisma.BookingItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BookingItemUpdateToOneWithWhereWithoutCheckinInput, Prisma.BookingItemUpdateWithoutCheckinInput>, Prisma.BookingItemUncheckedUpdateWithoutCheckinInput>
}

export type BookingItemCreateWithoutPriceTierInput = {
  id?: string
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  booking: Prisma.BookingCreateNestedOneWithoutItemsInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutBookingItemInput
  checkin?: Prisma.CheckinCreateNestedOneWithoutBookingItemInput
}

export type BookingItemUncheckedCreateWithoutPriceTierInput = {
  id?: string
  bookingId: string
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  checkin?: Prisma.CheckinUncheckedCreateNestedOneWithoutBookingItemInput
}

export type BookingItemCreateOrConnectWithoutPriceTierInput = {
  where: Prisma.BookingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutPriceTierInput, Prisma.BookingItemUncheckedCreateWithoutPriceTierInput>
}

export type BookingItemCreateManyPriceTierInputEnvelope = {
  data: Prisma.BookingItemCreateManyPriceTierInput | Prisma.BookingItemCreateManyPriceTierInput[]
  skipDuplicates?: boolean
}

export type BookingItemUpsertWithWhereUniqueWithoutPriceTierInput = {
  where: Prisma.BookingItemWhereUniqueInput
  update: Prisma.XOR<Prisma.BookingItemUpdateWithoutPriceTierInput, Prisma.BookingItemUncheckedUpdateWithoutPriceTierInput>
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutPriceTierInput, Prisma.BookingItemUncheckedCreateWithoutPriceTierInput>
}

export type BookingItemUpdateWithWhereUniqueWithoutPriceTierInput = {
  where: Prisma.BookingItemWhereUniqueInput
  data: Prisma.XOR<Prisma.BookingItemUpdateWithoutPriceTierInput, Prisma.BookingItemUncheckedUpdateWithoutPriceTierInput>
}

export type BookingItemUpdateManyWithWhereWithoutPriceTierInput = {
  where: Prisma.BookingItemScalarWhereInput
  data: Prisma.XOR<Prisma.BookingItemUpdateManyMutationInput, Prisma.BookingItemUncheckedUpdateManyWithoutPriceTierInput>
}

export type BookingItemScalarWhereInput = {
  AND?: Prisma.BookingItemScalarWhereInput | Prisma.BookingItemScalarWhereInput[]
  OR?: Prisma.BookingItemScalarWhereInput[]
  NOT?: Prisma.BookingItemScalarWhereInput | Prisma.BookingItemScalarWhereInput[]
  id?: Prisma.StringFilter<"BookingItem"> | string
  bookingId?: Prisma.StringFilter<"BookingItem"> | string
  priceTierId?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  tripSeatId?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerName?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerPhone?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  passengerEmail?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  ticketReference?: Prisma.StringNullableFilter<"BookingItem"> | string | null
  status?: Prisma.EnumCheckinStatusFilter<"BookingItem"> | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFilter<"BookingItem"> | Date | string
}

export type BookingItemCreateWithoutTripSeatInput = {
  id?: string
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  booking: Prisma.BookingCreateNestedOneWithoutItemsInput
  priceTier?: Prisma.PriceTierCreateNestedOneWithoutBookingItemsInput
  checkin?: Prisma.CheckinCreateNestedOneWithoutBookingItemInput
}

export type BookingItemUncheckedCreateWithoutTripSeatInput = {
  id?: string
  bookingId: string
  priceTierId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  checkin?: Prisma.CheckinUncheckedCreateNestedOneWithoutBookingItemInput
}

export type BookingItemCreateOrConnectWithoutTripSeatInput = {
  where: Prisma.BookingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutTripSeatInput, Prisma.BookingItemUncheckedCreateWithoutTripSeatInput>
}

export type BookingItemUpsertWithoutTripSeatInput = {
  update: Prisma.XOR<Prisma.BookingItemUpdateWithoutTripSeatInput, Prisma.BookingItemUncheckedUpdateWithoutTripSeatInput>
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutTripSeatInput, Prisma.BookingItemUncheckedCreateWithoutTripSeatInput>
  where?: Prisma.BookingItemWhereInput
}

export type BookingItemUpdateToOneWithWhereWithoutTripSeatInput = {
  where?: Prisma.BookingItemWhereInput
  data: Prisma.XOR<Prisma.BookingItemUpdateWithoutTripSeatInput, Prisma.BookingItemUncheckedUpdateWithoutTripSeatInput>
}

export type BookingItemUpdateWithoutTripSeatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateOneRequiredWithoutItemsNestedInput
  priceTier?: Prisma.PriceTierUpdateOneWithoutBookingItemsNestedInput
  checkin?: Prisma.CheckinUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateWithoutTripSeatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  checkin?: Prisma.CheckinUncheckedUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemCreateWithoutBookingInput = {
  id?: string
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  priceTier?: Prisma.PriceTierCreateNestedOneWithoutBookingItemsInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutBookingItemInput
  checkin?: Prisma.CheckinCreateNestedOneWithoutBookingItemInput
}

export type BookingItemUncheckedCreateWithoutBookingInput = {
  id?: string
  priceTierId?: string | null
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  checkin?: Prisma.CheckinUncheckedCreateNestedOneWithoutBookingItemInput
}

export type BookingItemCreateOrConnectWithoutBookingInput = {
  where: Prisma.BookingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutBookingInput, Prisma.BookingItemUncheckedCreateWithoutBookingInput>
}

export type BookingItemCreateManyBookingInputEnvelope = {
  data: Prisma.BookingItemCreateManyBookingInput | Prisma.BookingItemCreateManyBookingInput[]
  skipDuplicates?: boolean
}

export type BookingItemUpsertWithWhereUniqueWithoutBookingInput = {
  where: Prisma.BookingItemWhereUniqueInput
  update: Prisma.XOR<Prisma.BookingItemUpdateWithoutBookingInput, Prisma.BookingItemUncheckedUpdateWithoutBookingInput>
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutBookingInput, Prisma.BookingItemUncheckedCreateWithoutBookingInput>
}

export type BookingItemUpdateWithWhereUniqueWithoutBookingInput = {
  where: Prisma.BookingItemWhereUniqueInput
  data: Prisma.XOR<Prisma.BookingItemUpdateWithoutBookingInput, Prisma.BookingItemUncheckedUpdateWithoutBookingInput>
}

export type BookingItemUpdateManyWithWhereWithoutBookingInput = {
  where: Prisma.BookingItemScalarWhereInput
  data: Prisma.XOR<Prisma.BookingItemUpdateManyMutationInput, Prisma.BookingItemUncheckedUpdateManyWithoutBookingInput>
}

export type BookingItemCreateWithoutCheckinInput = {
  id?: string
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
  booking: Prisma.BookingCreateNestedOneWithoutItemsInput
  priceTier?: Prisma.PriceTierCreateNestedOneWithoutBookingItemsInput
  tripSeat?: Prisma.TripSeatCreateNestedOneWithoutBookingItemInput
}

export type BookingItemUncheckedCreateWithoutCheckinInput = {
  id?: string
  bookingId: string
  priceTierId?: string | null
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
}

export type BookingItemCreateOrConnectWithoutCheckinInput = {
  where: Prisma.BookingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutCheckinInput, Prisma.BookingItemUncheckedCreateWithoutCheckinInput>
}

export type BookingItemUpsertWithoutCheckinInput = {
  update: Prisma.XOR<Prisma.BookingItemUpdateWithoutCheckinInput, Prisma.BookingItemUncheckedUpdateWithoutCheckinInput>
  create: Prisma.XOR<Prisma.BookingItemCreateWithoutCheckinInput, Prisma.BookingItemUncheckedCreateWithoutCheckinInput>
  where?: Prisma.BookingItemWhereInput
}

export type BookingItemUpdateToOneWithWhereWithoutCheckinInput = {
  where?: Prisma.BookingItemWhereInput
  data: Prisma.XOR<Prisma.BookingItemUpdateWithoutCheckinInput, Prisma.BookingItemUncheckedUpdateWithoutCheckinInput>
}

export type BookingItemUpdateWithoutCheckinInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateOneRequiredWithoutItemsNestedInput
  priceTier?: Prisma.PriceTierUpdateOneWithoutBookingItemsNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateWithoutCheckinInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BookingItemCreateManyPriceTierInput = {
  id?: string
  bookingId: string
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
}

export type BookingItemUpdateWithoutPriceTierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateOneRequiredWithoutItemsNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutBookingItemNestedInput
  checkin?: Prisma.CheckinUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateWithoutPriceTierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  checkin?: Prisma.CheckinUncheckedUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateManyWithoutPriceTierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BookingItemCreateManyBookingInput = {
  id?: string
  priceTierId?: string | null
  tripSeatId?: string | null
  passengerName?: string | null
  passengerPhone?: string | null
  passengerEmail?: string | null
  ticketReference?: string | null
  status?: $Enums.CheckinStatus
  createdAt?: Date | string
}

export type BookingItemUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  priceTier?: Prisma.PriceTierUpdateOneWithoutBookingItemsNestedInput
  tripSeat?: Prisma.TripSeatUpdateOneWithoutBookingItemNestedInput
  checkin?: Prisma.CheckinUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  checkin?: Prisma.CheckinUncheckedUpdateOneWithoutBookingItemNestedInput
}

export type BookingItemUncheckedUpdateManyWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  priceTierId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tripSeatId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passengerEmail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ticketReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumCheckinStatusFieldUpdateOperationsInput | $Enums.CheckinStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BookingItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookingId?: boolean
  priceTierId?: boolean
  tripSeatId?: boolean
  passengerName?: boolean
  passengerPhone?: boolean
  passengerEmail?: boolean
  ticketReference?: boolean
  status?: boolean
  createdAt?: boolean
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
  priceTier?: boolean | Prisma.BookingItem$priceTierArgs<ExtArgs>
  tripSeat?: boolean | Prisma.BookingItem$tripSeatArgs<ExtArgs>
  checkin?: boolean | Prisma.BookingItem$checkinArgs<ExtArgs>
}, ExtArgs["result"]["bookingItem"]>

export type BookingItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookingId?: boolean
  priceTierId?: boolean
  tripSeatId?: boolean
  passengerName?: boolean
  passengerPhone?: boolean
  passengerEmail?: boolean
  ticketReference?: boolean
  status?: boolean
  createdAt?: boolean
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
  priceTier?: boolean | Prisma.BookingItem$priceTierArgs<ExtArgs>
  tripSeat?: boolean | Prisma.BookingItem$tripSeatArgs<ExtArgs>
}, ExtArgs["result"]["bookingItem"]>

export type BookingItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  bookingId?: boolean
  priceTierId?: boolean
  tripSeatId?: boolean
  passengerName?: boolean
  passengerPhone?: boolean
  passengerEmail?: boolean
  ticketReference?: boolean
  status?: boolean
  createdAt?: boolean
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
  priceTier?: boolean | Prisma.BookingItem$priceTierArgs<ExtArgs>
  tripSeat?: boolean | Prisma.BookingItem$tripSeatArgs<ExtArgs>
}, ExtArgs["result"]["bookingItem"]>

export type BookingItemSelectScalar = {
  id?: boolean
  bookingId?: boolean
  priceTierId?: boolean
  tripSeatId?: boolean
  passengerName?: boolean
  passengerPhone?: boolean
  passengerEmail?: boolean
  ticketReference?: boolean
  status?: boolean
  createdAt?: boolean
}

export type BookingItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bookingId" | "priceTierId" | "tripSeatId" | "passengerName" | "passengerPhone" | "passengerEmail" | "ticketReference" | "status" | "createdAt", ExtArgs["result"]["bookingItem"]>
export type BookingItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
  priceTier?: boolean | Prisma.BookingItem$priceTierArgs<ExtArgs>
  tripSeat?: boolean | Prisma.BookingItem$tripSeatArgs<ExtArgs>
  checkin?: boolean | Prisma.BookingItem$checkinArgs<ExtArgs>
}
export type BookingItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
  priceTier?: boolean | Prisma.BookingItem$priceTierArgs<ExtArgs>
  tripSeat?: boolean | Prisma.BookingItem$tripSeatArgs<ExtArgs>
}
export type BookingItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
  priceTier?: boolean | Prisma.BookingItem$priceTierArgs<ExtArgs>
  tripSeat?: boolean | Prisma.BookingItem$tripSeatArgs<ExtArgs>
}

export type $BookingItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BookingItem"
  objects: {
    booking: Prisma.$BookingPayload<ExtArgs>
    priceTier: Prisma.$PriceTierPayload<ExtArgs> | null
    tripSeat: Prisma.$TripSeatPayload<ExtArgs> | null
    checkin: Prisma.$CheckinPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    bookingId: string
    priceTierId: string | null
    tripSeatId: string | null
    passengerName: string | null
    passengerPhone: string | null
    passengerEmail: string | null
    ticketReference: string | null
    status: $Enums.CheckinStatus
    createdAt: Date
  }, ExtArgs["result"]["bookingItem"]>
  composites: {}
}

export type BookingItemGetPayload<S extends boolean | null | undefined | BookingItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BookingItemPayload, S>

export type BookingItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BookingItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BookingItemCountAggregateInputType | true
  }

export interface BookingItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BookingItem'], meta: { name: 'BookingItem' } }
  /**
   * Find zero or one BookingItem that matches the filter.
   * @param {BookingItemFindUniqueArgs} args - Arguments to find a BookingItem
   * @example
   * // Get one BookingItem
   * const bookingItem = await prisma.bookingItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BookingItemFindUniqueArgs>(args: Prisma.SelectSubset<T, BookingItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BookingItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BookingItemFindUniqueOrThrowArgs} args - Arguments to find a BookingItem
   * @example
   * // Get one BookingItem
   * const bookingItem = await prisma.bookingItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BookingItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BookingItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BookingItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemFindFirstArgs} args - Arguments to find a BookingItem
   * @example
   * // Get one BookingItem
   * const bookingItem = await prisma.bookingItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BookingItemFindFirstArgs>(args?: Prisma.SelectSubset<T, BookingItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BookingItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemFindFirstOrThrowArgs} args - Arguments to find a BookingItem
   * @example
   * // Get one BookingItem
   * const bookingItem = await prisma.bookingItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BookingItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BookingItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BookingItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BookingItems
   * const bookingItems = await prisma.bookingItem.findMany()
   * 
   * // Get first 10 BookingItems
   * const bookingItems = await prisma.bookingItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bookingItemWithIdOnly = await prisma.bookingItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BookingItemFindManyArgs>(args?: Prisma.SelectSubset<T, BookingItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BookingItem.
   * @param {BookingItemCreateArgs} args - Arguments to create a BookingItem.
   * @example
   * // Create one BookingItem
   * const BookingItem = await prisma.bookingItem.create({
   *   data: {
   *     // ... data to create a BookingItem
   *   }
   * })
   * 
   */
  create<T extends BookingItemCreateArgs>(args: Prisma.SelectSubset<T, BookingItemCreateArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BookingItems.
   * @param {BookingItemCreateManyArgs} args - Arguments to create many BookingItems.
   * @example
   * // Create many BookingItems
   * const bookingItem = await prisma.bookingItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BookingItemCreateManyArgs>(args?: Prisma.SelectSubset<T, BookingItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BookingItems and returns the data saved in the database.
   * @param {BookingItemCreateManyAndReturnArgs} args - Arguments to create many BookingItems.
   * @example
   * // Create many BookingItems
   * const bookingItem = await prisma.bookingItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BookingItems and only return the `id`
   * const bookingItemWithIdOnly = await prisma.bookingItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BookingItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BookingItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BookingItem.
   * @param {BookingItemDeleteArgs} args - Arguments to delete one BookingItem.
   * @example
   * // Delete one BookingItem
   * const BookingItem = await prisma.bookingItem.delete({
   *   where: {
   *     // ... filter to delete one BookingItem
   *   }
   * })
   * 
   */
  delete<T extends BookingItemDeleteArgs>(args: Prisma.SelectSubset<T, BookingItemDeleteArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BookingItem.
   * @param {BookingItemUpdateArgs} args - Arguments to update one BookingItem.
   * @example
   * // Update one BookingItem
   * const bookingItem = await prisma.bookingItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BookingItemUpdateArgs>(args: Prisma.SelectSubset<T, BookingItemUpdateArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BookingItems.
   * @param {BookingItemDeleteManyArgs} args - Arguments to filter BookingItems to delete.
   * @example
   * // Delete a few BookingItems
   * const { count } = await prisma.bookingItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BookingItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, BookingItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BookingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BookingItems
   * const bookingItem = await prisma.bookingItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BookingItemUpdateManyArgs>(args: Prisma.SelectSubset<T, BookingItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BookingItems and returns the data updated in the database.
   * @param {BookingItemUpdateManyAndReturnArgs} args - Arguments to update many BookingItems.
   * @example
   * // Update many BookingItems
   * const bookingItem = await prisma.bookingItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BookingItems and only return the `id`
   * const bookingItemWithIdOnly = await prisma.bookingItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BookingItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BookingItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BookingItem.
   * @param {BookingItemUpsertArgs} args - Arguments to update or create a BookingItem.
   * @example
   * // Update or create a BookingItem
   * const bookingItem = await prisma.bookingItem.upsert({
   *   create: {
   *     // ... data to create a BookingItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BookingItem we want to update
   *   }
   * })
   */
  upsert<T extends BookingItemUpsertArgs>(args: Prisma.SelectSubset<T, BookingItemUpsertArgs<ExtArgs>>): Prisma.Prisma__BookingItemClient<runtime.Types.Result.GetResult<Prisma.$BookingItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BookingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemCountArgs} args - Arguments to filter BookingItems to count.
   * @example
   * // Count the number of BookingItems
   * const count = await prisma.bookingItem.count({
   *   where: {
   *     // ... the filter for the BookingItems we want to count
   *   }
   * })
  **/
  count<T extends BookingItemCountArgs>(
    args?: Prisma.Subset<T, BookingItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BookingItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BookingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BookingItemAggregateArgs>(args: Prisma.Subset<T, BookingItemAggregateArgs>): Prisma.PrismaPromise<GetBookingItemAggregateType<T>>

  /**
   * Group by BookingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BookingItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BookingItemGroupByArgs['orderBy'] }
      : { orderBy?: BookingItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BookingItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBookingItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BookingItem model
 */
readonly fields: BookingItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BookingItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BookingItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  booking<T extends Prisma.BookingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BookingDefaultArgs<ExtArgs>>): Prisma.Prisma__BookingClient<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  priceTier<T extends Prisma.BookingItem$priceTierArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BookingItem$priceTierArgs<ExtArgs>>): Prisma.Prisma__PriceTierClient<runtime.Types.Result.GetResult<Prisma.$PriceTierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  tripSeat<T extends Prisma.BookingItem$tripSeatArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BookingItem$tripSeatArgs<ExtArgs>>): Prisma.Prisma__TripSeatClient<runtime.Types.Result.GetResult<Prisma.$TripSeatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  checkin<T extends Prisma.BookingItem$checkinArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BookingItem$checkinArgs<ExtArgs>>): Prisma.Prisma__CheckinClient<runtime.Types.Result.GetResult<Prisma.$CheckinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BookingItem model
 */
export interface BookingItemFieldRefs {
  readonly id: Prisma.FieldRef<"BookingItem", 'String'>
  readonly bookingId: Prisma.FieldRef<"BookingItem", 'String'>
  readonly priceTierId: Prisma.FieldRef<"BookingItem", 'String'>
  readonly tripSeatId: Prisma.FieldRef<"BookingItem", 'String'>
  readonly passengerName: Prisma.FieldRef<"BookingItem", 'String'>
  readonly passengerPhone: Prisma.FieldRef<"BookingItem", 'String'>
  readonly passengerEmail: Prisma.FieldRef<"BookingItem", 'String'>
  readonly ticketReference: Prisma.FieldRef<"BookingItem", 'String'>
  readonly status: Prisma.FieldRef<"BookingItem", 'CheckinStatus'>
  readonly createdAt: Prisma.FieldRef<"BookingItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BookingItem findUnique
 */
export type BookingItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * Filter, which BookingItem to fetch.
   */
  where: Prisma.BookingItemWhereUniqueInput
}

/**
 * BookingItem findUniqueOrThrow
 */
export type BookingItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * Filter, which BookingItem to fetch.
   */
  where: Prisma.BookingItemWhereUniqueInput
}

/**
 * BookingItem findFirst
 */
export type BookingItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * Filter, which BookingItem to fetch.
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookingItems to fetch.
   */
  orderBy?: Prisma.BookingItemOrderByWithRelationInput | Prisma.BookingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BookingItems.
   */
  cursor?: Prisma.BookingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BookingItems.
   */
  distinct?: Prisma.BookingItemScalarFieldEnum | Prisma.BookingItemScalarFieldEnum[]
}

/**
 * BookingItem findFirstOrThrow
 */
export type BookingItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * Filter, which BookingItem to fetch.
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookingItems to fetch.
   */
  orderBy?: Prisma.BookingItemOrderByWithRelationInput | Prisma.BookingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BookingItems.
   */
  cursor?: Prisma.BookingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BookingItems.
   */
  distinct?: Prisma.BookingItemScalarFieldEnum | Prisma.BookingItemScalarFieldEnum[]
}

/**
 * BookingItem findMany
 */
export type BookingItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * Filter, which BookingItems to fetch.
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BookingItems to fetch.
   */
  orderBy?: Prisma.BookingItemOrderByWithRelationInput | Prisma.BookingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BookingItems.
   */
  cursor?: Prisma.BookingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BookingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BookingItems.
   */
  skip?: number
  distinct?: Prisma.BookingItemScalarFieldEnum | Prisma.BookingItemScalarFieldEnum[]
}

/**
 * BookingItem create
 */
export type BookingItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * The data needed to create a BookingItem.
   */
  data: Prisma.XOR<Prisma.BookingItemCreateInput, Prisma.BookingItemUncheckedCreateInput>
}

/**
 * BookingItem createMany
 */
export type BookingItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BookingItems.
   */
  data: Prisma.BookingItemCreateManyInput | Prisma.BookingItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BookingItem createManyAndReturn
 */
export type BookingItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * The data used to create many BookingItems.
   */
  data: Prisma.BookingItemCreateManyInput | Prisma.BookingItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BookingItem update
 */
export type BookingItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * The data needed to update a BookingItem.
   */
  data: Prisma.XOR<Prisma.BookingItemUpdateInput, Prisma.BookingItemUncheckedUpdateInput>
  /**
   * Choose, which BookingItem to update.
   */
  where: Prisma.BookingItemWhereUniqueInput
}

/**
 * BookingItem updateMany
 */
export type BookingItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BookingItems.
   */
  data: Prisma.XOR<Prisma.BookingItemUpdateManyMutationInput, Prisma.BookingItemUncheckedUpdateManyInput>
  /**
   * Filter which BookingItems to update
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * Limit how many BookingItems to update.
   */
  limit?: number
}

/**
 * BookingItem updateManyAndReturn
 */
export type BookingItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * The data used to update BookingItems.
   */
  data: Prisma.XOR<Prisma.BookingItemUpdateManyMutationInput, Prisma.BookingItemUncheckedUpdateManyInput>
  /**
   * Filter which BookingItems to update
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * Limit how many BookingItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BookingItem upsert
 */
export type BookingItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * The filter to search for the BookingItem to update in case it exists.
   */
  where: Prisma.BookingItemWhereUniqueInput
  /**
   * In case the BookingItem found by the `where` argument doesn't exist, create a new BookingItem with this data.
   */
  create: Prisma.XOR<Prisma.BookingItemCreateInput, Prisma.BookingItemUncheckedCreateInput>
  /**
   * In case the BookingItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BookingItemUpdateInput, Prisma.BookingItemUncheckedUpdateInput>
}

/**
 * BookingItem delete
 */
export type BookingItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
  /**
   * Filter which BookingItem to delete.
   */
  where: Prisma.BookingItemWhereUniqueInput
}

/**
 * BookingItem deleteMany
 */
export type BookingItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BookingItems to delete
   */
  where?: Prisma.BookingItemWhereInput
  /**
   * Limit how many BookingItems to delete.
   */
  limit?: number
}

/**
 * BookingItem.priceTier
 */
export type BookingItem$priceTierArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceTier
   */
  select?: Prisma.PriceTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceTier
   */
  omit?: Prisma.PriceTierOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PriceTierInclude<ExtArgs> | null
  where?: Prisma.PriceTierWhereInput
}

/**
 * BookingItem.tripSeat
 */
export type BookingItem$tripSeatArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripSeat
   */
  select?: Prisma.TripSeatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripSeat
   */
  omit?: Prisma.TripSeatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripSeatInclude<ExtArgs> | null
  where?: Prisma.TripSeatWhereInput
}

/**
 * BookingItem.checkin
 */
export type BookingItem$checkinArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkin
   */
  select?: Prisma.CheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkin
   */
  omit?: Prisma.CheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckinInclude<ExtArgs> | null
  where?: Prisma.CheckinWhereInput
}

/**
 * BookingItem without action
 */
export type BookingItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BookingItem
   */
  select?: Prisma.BookingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BookingItem
   */
  omit?: Prisma.BookingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingItemInclude<ExtArgs> | null
}
