
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Trip` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Trip
 * 
 */
export type TripModel = runtime.Types.Result.DefaultSelection<Prisma.$TripPayload>

export type AggregateTrip = {
  _count: TripCountAggregateOutputType | null
  _avg: TripAvgAggregateOutputType | null
  _sum: TripSumAggregateOutputType | null
  _min: TripMinAggregateOutputType | null
  _max: TripMaxAggregateOutputType | null
}

export type TripAvgAggregateOutputType = {
  durationMinutes: number | null
}

export type TripSumAggregateOutputType = {
  durationMinutes: number | null
}

export type TripMinAggregateOutputType = {
  id: string | null
  vesselId: string | null
  operatorId: string | null
  title: string | null
  description: string | null
  category: string | null
  externalReference: string | null
  durationMinutes: number | null
  isRecurring: boolean | null
  departurePort: string | null
  arrivalPort: string | null
  routeName: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type TripMaxAggregateOutputType = {
  id: string | null
  vesselId: string | null
  operatorId: string | null
  title: string | null
  description: string | null
  category: string | null
  externalReference: string | null
  durationMinutes: number | null
  isRecurring: boolean | null
  departurePort: string | null
  arrivalPort: string | null
  routeName: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type TripCountAggregateOutputType = {
  id: number
  vesselId: number
  operatorId: number
  title: number
  description: number
  category: number
  externalReference: number
  durationMinutes: number
  isRecurring: number
  amenities: number
  highlights: number
  departurePort: number
  arrivalPort: number
  routeName: number
  isActive: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type TripAvgAggregateInputType = {
  durationMinutes?: true
}

export type TripSumAggregateInputType = {
  durationMinutes?: true
}

export type TripMinAggregateInputType = {
  id?: true
  vesselId?: true
  operatorId?: true
  title?: true
  description?: true
  category?: true
  externalReference?: true
  durationMinutes?: true
  isRecurring?: true
  departurePort?: true
  arrivalPort?: true
  routeName?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type TripMaxAggregateInputType = {
  id?: true
  vesselId?: true
  operatorId?: true
  title?: true
  description?: true
  category?: true
  externalReference?: true
  durationMinutes?: true
  isRecurring?: true
  departurePort?: true
  arrivalPort?: true
  routeName?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type TripCountAggregateInputType = {
  id?: true
  vesselId?: true
  operatorId?: true
  title?: true
  description?: true
  category?: true
  externalReference?: true
  durationMinutes?: true
  isRecurring?: true
  amenities?: true
  highlights?: true
  departurePort?: true
  arrivalPort?: true
  routeName?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type TripAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Trip to aggregate.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Trips
  **/
  _count?: true | TripCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TripAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TripSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TripMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TripMaxAggregateInputType
}

export type GetTripAggregateType<T extends TripAggregateArgs> = {
      [P in keyof T & keyof AggregateTrip]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTrip[P]>
    : Prisma.GetScalarType<T[P], AggregateTrip[P]>
}




export type TripGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TripWhereInput
  orderBy?: Prisma.TripOrderByWithAggregationInput | Prisma.TripOrderByWithAggregationInput[]
  by: Prisma.TripScalarFieldEnum[] | Prisma.TripScalarFieldEnum
  having?: Prisma.TripScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TripCountAggregateInputType | true
  _avg?: TripAvgAggregateInputType
  _sum?: TripSumAggregateInputType
  _min?: TripMinAggregateInputType
  _max?: TripMaxAggregateInputType
}

export type TripGroupByOutputType = {
  id: string
  vesselId: string
  operatorId: string | null
  title: string
  description: string | null
  category: string | null
  externalReference: string | null
  durationMinutes: number | null
  isRecurring: boolean
  amenities: runtime.JsonValue | null
  highlights: runtime.JsonValue | null
  departurePort: string | null
  arrivalPort: string | null
  routeName: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: TripCountAggregateOutputType | null
  _avg: TripAvgAggregateOutputType | null
  _sum: TripSumAggregateOutputType | null
  _min: TripMinAggregateOutputType | null
  _max: TripMaxAggregateOutputType | null
}

type GetTripGroupByPayload<T extends TripGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TripGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TripGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TripGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TripGroupByOutputType[P]>
      }
    >
  >



export type TripWhereInput = {
  AND?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  OR?: Prisma.TripWhereInput[]
  NOT?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  id?: Prisma.StringFilter<"Trip"> | string
  vesselId?: Prisma.StringFilter<"Trip"> | string
  operatorId?: Prisma.StringNullableFilter<"Trip"> | string | null
  title?: Prisma.StringFilter<"Trip"> | string
  description?: Prisma.StringNullableFilter<"Trip"> | string | null
  category?: Prisma.StringNullableFilter<"Trip"> | string | null
  externalReference?: Prisma.StringNullableFilter<"Trip"> | string | null
  durationMinutes?: Prisma.IntNullableFilter<"Trip"> | number | null
  isRecurring?: Prisma.BoolFilter<"Trip"> | boolean
  amenities?: Prisma.JsonNullableFilter<"Trip">
  highlights?: Prisma.JsonNullableFilter<"Trip">
  departurePort?: Prisma.StringNullableFilter<"Trip"> | string | null
  arrivalPort?: Prisma.StringNullableFilter<"Trip"> | string | null
  routeName?: Prisma.StringNullableFilter<"Trip"> | string | null
  isActive?: Prisma.BoolFilter<"Trip"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Trip"> | Date | string | null
  vessel?: Prisma.XOR<Prisma.VesselScalarRelationFilter, Prisma.VesselWhereInput>
  operator?: Prisma.XOR<Prisma.OperatorNullableScalarRelationFilter, Prisma.OperatorWhereInput> | null
  schedules?: Prisma.TripScheduleListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
}

export type TripOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  vesselId?: Prisma.SortOrder
  operatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  externalReference?: Prisma.SortOrderInput | Prisma.SortOrder
  durationMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  isRecurring?: Prisma.SortOrder
  amenities?: Prisma.SortOrderInput | Prisma.SortOrder
  highlights?: Prisma.SortOrderInput | Prisma.SortOrder
  departurePort?: Prisma.SortOrderInput | Prisma.SortOrder
  arrivalPort?: Prisma.SortOrderInput | Prisma.SortOrder
  routeName?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  vessel?: Prisma.VesselOrderByWithRelationInput
  operator?: Prisma.OperatorOrderByWithRelationInput
  schedules?: Prisma.TripScheduleOrderByRelationAggregateInput
  reviews?: Prisma.ReviewOrderByRelationAggregateInput
}

export type TripWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  OR?: Prisma.TripWhereInput[]
  NOT?: Prisma.TripWhereInput | Prisma.TripWhereInput[]
  vesselId?: Prisma.StringFilter<"Trip"> | string
  operatorId?: Prisma.StringNullableFilter<"Trip"> | string | null
  title?: Prisma.StringFilter<"Trip"> | string
  description?: Prisma.StringNullableFilter<"Trip"> | string | null
  category?: Prisma.StringNullableFilter<"Trip"> | string | null
  externalReference?: Prisma.StringNullableFilter<"Trip"> | string | null
  durationMinutes?: Prisma.IntNullableFilter<"Trip"> | number | null
  isRecurring?: Prisma.BoolFilter<"Trip"> | boolean
  amenities?: Prisma.JsonNullableFilter<"Trip">
  highlights?: Prisma.JsonNullableFilter<"Trip">
  departurePort?: Prisma.StringNullableFilter<"Trip"> | string | null
  arrivalPort?: Prisma.StringNullableFilter<"Trip"> | string | null
  routeName?: Prisma.StringNullableFilter<"Trip"> | string | null
  isActive?: Prisma.BoolFilter<"Trip"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Trip"> | Date | string | null
  vessel?: Prisma.XOR<Prisma.VesselScalarRelationFilter, Prisma.VesselWhereInput>
  operator?: Prisma.XOR<Prisma.OperatorNullableScalarRelationFilter, Prisma.OperatorWhereInput> | null
  schedules?: Prisma.TripScheduleListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
}, "id">

export type TripOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  vesselId?: Prisma.SortOrder
  operatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  externalReference?: Prisma.SortOrderInput | Prisma.SortOrder
  durationMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  isRecurring?: Prisma.SortOrder
  amenities?: Prisma.SortOrderInput | Prisma.SortOrder
  highlights?: Prisma.SortOrderInput | Prisma.SortOrder
  departurePort?: Prisma.SortOrderInput | Prisma.SortOrder
  arrivalPort?: Prisma.SortOrderInput | Prisma.SortOrder
  routeName?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TripCountOrderByAggregateInput
  _avg?: Prisma.TripAvgOrderByAggregateInput
  _max?: Prisma.TripMaxOrderByAggregateInput
  _min?: Prisma.TripMinOrderByAggregateInput
  _sum?: Prisma.TripSumOrderByAggregateInput
}

export type TripScalarWhereWithAggregatesInput = {
  AND?: Prisma.TripScalarWhereWithAggregatesInput | Prisma.TripScalarWhereWithAggregatesInput[]
  OR?: Prisma.TripScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TripScalarWhereWithAggregatesInput | Prisma.TripScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  vesselId?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  operatorId?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  title?: Prisma.StringWithAggregatesFilter<"Trip"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  category?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  externalReference?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  durationMinutes?: Prisma.IntNullableWithAggregatesFilter<"Trip"> | number | null
  isRecurring?: Prisma.BoolWithAggregatesFilter<"Trip"> | boolean
  amenities?: Prisma.JsonNullableWithAggregatesFilter<"Trip">
  highlights?: Prisma.JsonNullableWithAggregatesFilter<"Trip">
  departurePort?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  arrivalPort?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  routeName?: Prisma.StringNullableWithAggregatesFilter<"Trip"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"Trip"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Trip"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Trip"> | Date | string | null
}

export type TripCreateInput = {
  id?: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  vessel: Prisma.VesselCreateNestedOneWithoutTripsInput
  operator?: Prisma.OperatorCreateNestedOneWithoutTripsInput
  schedules?: Prisma.TripScheduleCreateNestedManyWithoutTripInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateInput = {
  id?: string
  vesselId: string
  operatorId?: string | null
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  schedules?: Prisma.TripScheduleUncheckedCreateNestedManyWithoutTripInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTripInput
}

export type TripUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vessel?: Prisma.VesselUpdateOneRequiredWithoutTripsNestedInput
  operator?: Prisma.OperatorUpdateOneWithoutTripsNestedInput
  schedules?: Prisma.TripScheduleUpdateManyWithoutTripNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vesselId?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  schedules?: Prisma.TripScheduleUncheckedUpdateManyWithoutTripNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateManyInput = {
  id?: string
  vesselId: string
  operatorId?: string | null
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TripUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TripUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vesselId?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TripListRelationFilter = {
  every?: Prisma.TripWhereInput
  some?: Prisma.TripWhereInput
  none?: Prisma.TripWhereInput
}

export type TripOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TripCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vesselId?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  externalReference?: Prisma.SortOrder
  durationMinutes?: Prisma.SortOrder
  isRecurring?: Prisma.SortOrder
  amenities?: Prisma.SortOrder
  highlights?: Prisma.SortOrder
  departurePort?: Prisma.SortOrder
  arrivalPort?: Prisma.SortOrder
  routeName?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TripAvgOrderByAggregateInput = {
  durationMinutes?: Prisma.SortOrder
}

export type TripMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vesselId?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  externalReference?: Prisma.SortOrder
  durationMinutes?: Prisma.SortOrder
  isRecurring?: Prisma.SortOrder
  departurePort?: Prisma.SortOrder
  arrivalPort?: Prisma.SortOrder
  routeName?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TripMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vesselId?: Prisma.SortOrder
  operatorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  externalReference?: Prisma.SortOrder
  durationMinutes?: Prisma.SortOrder
  isRecurring?: Prisma.SortOrder
  departurePort?: Prisma.SortOrder
  arrivalPort?: Prisma.SortOrder
  routeName?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TripSumOrderByAggregateInput = {
  durationMinutes?: Prisma.SortOrder
}

export type TripScalarRelationFilter = {
  is?: Prisma.TripWhereInput
  isNot?: Prisma.TripWhereInput
}

export type TripCreateNestedManyWithoutOperatorInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutOperatorInput, Prisma.TripUncheckedCreateWithoutOperatorInput> | Prisma.TripCreateWithoutOperatorInput[] | Prisma.TripUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutOperatorInput | Prisma.TripCreateOrConnectWithoutOperatorInput[]
  createMany?: Prisma.TripCreateManyOperatorInputEnvelope
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
}

export type TripUncheckedCreateNestedManyWithoutOperatorInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutOperatorInput, Prisma.TripUncheckedCreateWithoutOperatorInput> | Prisma.TripCreateWithoutOperatorInput[] | Prisma.TripUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutOperatorInput | Prisma.TripCreateOrConnectWithoutOperatorInput[]
  createMany?: Prisma.TripCreateManyOperatorInputEnvelope
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
}

export type TripUpdateManyWithoutOperatorNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutOperatorInput, Prisma.TripUncheckedCreateWithoutOperatorInput> | Prisma.TripCreateWithoutOperatorInput[] | Prisma.TripUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutOperatorInput | Prisma.TripCreateOrConnectWithoutOperatorInput[]
  upsert?: Prisma.TripUpsertWithWhereUniqueWithoutOperatorInput | Prisma.TripUpsertWithWhereUniqueWithoutOperatorInput[]
  createMany?: Prisma.TripCreateManyOperatorInputEnvelope
  set?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  disconnect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  delete?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  update?: Prisma.TripUpdateWithWhereUniqueWithoutOperatorInput | Prisma.TripUpdateWithWhereUniqueWithoutOperatorInput[]
  updateMany?: Prisma.TripUpdateManyWithWhereWithoutOperatorInput | Prisma.TripUpdateManyWithWhereWithoutOperatorInput[]
  deleteMany?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
}

export type TripUncheckedUpdateManyWithoutOperatorNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutOperatorInput, Prisma.TripUncheckedCreateWithoutOperatorInput> | Prisma.TripCreateWithoutOperatorInput[] | Prisma.TripUncheckedCreateWithoutOperatorInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutOperatorInput | Prisma.TripCreateOrConnectWithoutOperatorInput[]
  upsert?: Prisma.TripUpsertWithWhereUniqueWithoutOperatorInput | Prisma.TripUpsertWithWhereUniqueWithoutOperatorInput[]
  createMany?: Prisma.TripCreateManyOperatorInputEnvelope
  set?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  disconnect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  delete?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  update?: Prisma.TripUpdateWithWhereUniqueWithoutOperatorInput | Prisma.TripUpdateWithWhereUniqueWithoutOperatorInput[]
  updateMany?: Prisma.TripUpdateManyWithWhereWithoutOperatorInput | Prisma.TripUpdateManyWithWhereWithoutOperatorInput[]
  deleteMany?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
}

export type TripCreateNestedManyWithoutVesselInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutVesselInput, Prisma.TripUncheckedCreateWithoutVesselInput> | Prisma.TripCreateWithoutVesselInput[] | Prisma.TripUncheckedCreateWithoutVesselInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutVesselInput | Prisma.TripCreateOrConnectWithoutVesselInput[]
  createMany?: Prisma.TripCreateManyVesselInputEnvelope
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
}

export type TripUncheckedCreateNestedManyWithoutVesselInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutVesselInput, Prisma.TripUncheckedCreateWithoutVesselInput> | Prisma.TripCreateWithoutVesselInput[] | Prisma.TripUncheckedCreateWithoutVesselInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutVesselInput | Prisma.TripCreateOrConnectWithoutVesselInput[]
  createMany?: Prisma.TripCreateManyVesselInputEnvelope
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
}

export type TripUpdateManyWithoutVesselNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutVesselInput, Prisma.TripUncheckedCreateWithoutVesselInput> | Prisma.TripCreateWithoutVesselInput[] | Prisma.TripUncheckedCreateWithoutVesselInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutVesselInput | Prisma.TripCreateOrConnectWithoutVesselInput[]
  upsert?: Prisma.TripUpsertWithWhereUniqueWithoutVesselInput | Prisma.TripUpsertWithWhereUniqueWithoutVesselInput[]
  createMany?: Prisma.TripCreateManyVesselInputEnvelope
  set?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  disconnect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  delete?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  update?: Prisma.TripUpdateWithWhereUniqueWithoutVesselInput | Prisma.TripUpdateWithWhereUniqueWithoutVesselInput[]
  updateMany?: Prisma.TripUpdateManyWithWhereWithoutVesselInput | Prisma.TripUpdateManyWithWhereWithoutVesselInput[]
  deleteMany?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
}

export type TripUncheckedUpdateManyWithoutVesselNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutVesselInput, Prisma.TripUncheckedCreateWithoutVesselInput> | Prisma.TripCreateWithoutVesselInput[] | Prisma.TripUncheckedCreateWithoutVesselInput[]
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutVesselInput | Prisma.TripCreateOrConnectWithoutVesselInput[]
  upsert?: Prisma.TripUpsertWithWhereUniqueWithoutVesselInput | Prisma.TripUpsertWithWhereUniqueWithoutVesselInput[]
  createMany?: Prisma.TripCreateManyVesselInputEnvelope
  set?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  disconnect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  delete?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  connect?: Prisma.TripWhereUniqueInput | Prisma.TripWhereUniqueInput[]
  update?: Prisma.TripUpdateWithWhereUniqueWithoutVesselInput | Prisma.TripUpdateWithWhereUniqueWithoutVesselInput[]
  updateMany?: Prisma.TripUpdateManyWithWhereWithoutVesselInput | Prisma.TripUpdateManyWithWhereWithoutVesselInput[]
  deleteMany?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TripCreateNestedOneWithoutSchedulesInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutSchedulesInput, Prisma.TripUncheckedCreateWithoutSchedulesInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutSchedulesInput
  connect?: Prisma.TripWhereUniqueInput
}

export type TripUpdateOneRequiredWithoutSchedulesNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutSchedulesInput, Prisma.TripUncheckedCreateWithoutSchedulesInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutSchedulesInput
  upsert?: Prisma.TripUpsertWithoutSchedulesInput
  connect?: Prisma.TripWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TripUpdateToOneWithWhereWithoutSchedulesInput, Prisma.TripUpdateWithoutSchedulesInput>, Prisma.TripUncheckedUpdateWithoutSchedulesInput>
}

export type TripCreateNestedOneWithoutReviewsInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutReviewsInput, Prisma.TripUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutReviewsInput
  connect?: Prisma.TripWhereUniqueInput
}

export type TripUpdateOneRequiredWithoutReviewsNestedInput = {
  create?: Prisma.XOR<Prisma.TripCreateWithoutReviewsInput, Prisma.TripUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.TripCreateOrConnectWithoutReviewsInput
  upsert?: Prisma.TripUpsertWithoutReviewsInput
  connect?: Prisma.TripWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TripUpdateToOneWithWhereWithoutReviewsInput, Prisma.TripUpdateWithoutReviewsInput>, Prisma.TripUncheckedUpdateWithoutReviewsInput>
}

export type TripCreateWithoutOperatorInput = {
  id?: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  vessel: Prisma.VesselCreateNestedOneWithoutTripsInput
  schedules?: Prisma.TripScheduleCreateNestedManyWithoutTripInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutOperatorInput = {
  id?: string
  vesselId: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  schedules?: Prisma.TripScheduleUncheckedCreateNestedManyWithoutTripInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutOperatorInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutOperatorInput, Prisma.TripUncheckedCreateWithoutOperatorInput>
}

export type TripCreateManyOperatorInputEnvelope = {
  data: Prisma.TripCreateManyOperatorInput | Prisma.TripCreateManyOperatorInput[]
  skipDuplicates?: boolean
}

export type TripUpsertWithWhereUniqueWithoutOperatorInput = {
  where: Prisma.TripWhereUniqueInput
  update: Prisma.XOR<Prisma.TripUpdateWithoutOperatorInput, Prisma.TripUncheckedUpdateWithoutOperatorInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutOperatorInput, Prisma.TripUncheckedCreateWithoutOperatorInput>
}

export type TripUpdateWithWhereUniqueWithoutOperatorInput = {
  where: Prisma.TripWhereUniqueInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutOperatorInput, Prisma.TripUncheckedUpdateWithoutOperatorInput>
}

export type TripUpdateManyWithWhereWithoutOperatorInput = {
  where: Prisma.TripScalarWhereInput
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyWithoutOperatorInput>
}

export type TripScalarWhereInput = {
  AND?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
  OR?: Prisma.TripScalarWhereInput[]
  NOT?: Prisma.TripScalarWhereInput | Prisma.TripScalarWhereInput[]
  id?: Prisma.StringFilter<"Trip"> | string
  vesselId?: Prisma.StringFilter<"Trip"> | string
  operatorId?: Prisma.StringNullableFilter<"Trip"> | string | null
  title?: Prisma.StringFilter<"Trip"> | string
  description?: Prisma.StringNullableFilter<"Trip"> | string | null
  category?: Prisma.StringNullableFilter<"Trip"> | string | null
  externalReference?: Prisma.StringNullableFilter<"Trip"> | string | null
  durationMinutes?: Prisma.IntNullableFilter<"Trip"> | number | null
  isRecurring?: Prisma.BoolFilter<"Trip"> | boolean
  amenities?: Prisma.JsonNullableFilter<"Trip">
  highlights?: Prisma.JsonNullableFilter<"Trip">
  departurePort?: Prisma.StringNullableFilter<"Trip"> | string | null
  arrivalPort?: Prisma.StringNullableFilter<"Trip"> | string | null
  routeName?: Prisma.StringNullableFilter<"Trip"> | string | null
  isActive?: Prisma.BoolFilter<"Trip"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Trip"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Trip"> | Date | string | null
}

export type TripCreateWithoutVesselInput = {
  id?: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  operator?: Prisma.OperatorCreateNestedOneWithoutTripsInput
  schedules?: Prisma.TripScheduleCreateNestedManyWithoutTripInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutVesselInput = {
  id?: string
  operatorId?: string | null
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  schedules?: Prisma.TripScheduleUncheckedCreateNestedManyWithoutTripInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutVesselInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutVesselInput, Prisma.TripUncheckedCreateWithoutVesselInput>
}

export type TripCreateManyVesselInputEnvelope = {
  data: Prisma.TripCreateManyVesselInput | Prisma.TripCreateManyVesselInput[]
  skipDuplicates?: boolean
}

export type TripUpsertWithWhereUniqueWithoutVesselInput = {
  where: Prisma.TripWhereUniqueInput
  update: Prisma.XOR<Prisma.TripUpdateWithoutVesselInput, Prisma.TripUncheckedUpdateWithoutVesselInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutVesselInput, Prisma.TripUncheckedCreateWithoutVesselInput>
}

export type TripUpdateWithWhereUniqueWithoutVesselInput = {
  where: Prisma.TripWhereUniqueInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutVesselInput, Prisma.TripUncheckedUpdateWithoutVesselInput>
}

export type TripUpdateManyWithWhereWithoutVesselInput = {
  where: Prisma.TripScalarWhereInput
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyWithoutVesselInput>
}

export type TripCreateWithoutSchedulesInput = {
  id?: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  vessel: Prisma.VesselCreateNestedOneWithoutTripsInput
  operator?: Prisma.OperatorCreateNestedOneWithoutTripsInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutSchedulesInput = {
  id?: string
  vesselId: string
  operatorId?: string | null
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutSchedulesInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutSchedulesInput, Prisma.TripUncheckedCreateWithoutSchedulesInput>
}

export type TripUpsertWithoutSchedulesInput = {
  update: Prisma.XOR<Prisma.TripUpdateWithoutSchedulesInput, Prisma.TripUncheckedUpdateWithoutSchedulesInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutSchedulesInput, Prisma.TripUncheckedCreateWithoutSchedulesInput>
  where?: Prisma.TripWhereInput
}

export type TripUpdateToOneWithWhereWithoutSchedulesInput = {
  where?: Prisma.TripWhereInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutSchedulesInput, Prisma.TripUncheckedUpdateWithoutSchedulesInput>
}

export type TripUpdateWithoutSchedulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vessel?: Prisma.VesselUpdateOneRequiredWithoutTripsNestedInput
  operator?: Prisma.OperatorUpdateOneWithoutTripsNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutSchedulesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vesselId?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateWithoutReviewsInput = {
  id?: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  vessel: Prisma.VesselCreateNestedOneWithoutTripsInput
  operator?: Prisma.OperatorCreateNestedOneWithoutTripsInput
  schedules?: Prisma.TripScheduleCreateNestedManyWithoutTripInput
}

export type TripUncheckedCreateWithoutReviewsInput = {
  id?: string
  vesselId: string
  operatorId?: string | null
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  schedules?: Prisma.TripScheduleUncheckedCreateNestedManyWithoutTripInput
}

export type TripCreateOrConnectWithoutReviewsInput = {
  where: Prisma.TripWhereUniqueInput
  create: Prisma.XOR<Prisma.TripCreateWithoutReviewsInput, Prisma.TripUncheckedCreateWithoutReviewsInput>
}

export type TripUpsertWithoutReviewsInput = {
  update: Prisma.XOR<Prisma.TripUpdateWithoutReviewsInput, Prisma.TripUncheckedUpdateWithoutReviewsInput>
  create: Prisma.XOR<Prisma.TripCreateWithoutReviewsInput, Prisma.TripUncheckedCreateWithoutReviewsInput>
  where?: Prisma.TripWhereInput
}

export type TripUpdateToOneWithWhereWithoutReviewsInput = {
  where?: Prisma.TripWhereInput
  data: Prisma.XOR<Prisma.TripUpdateWithoutReviewsInput, Prisma.TripUncheckedUpdateWithoutReviewsInput>
}

export type TripUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vessel?: Prisma.VesselUpdateOneRequiredWithoutTripsNestedInput
  operator?: Prisma.OperatorUpdateOneWithoutTripsNestedInput
  schedules?: Prisma.TripScheduleUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vesselId?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  schedules?: Prisma.TripScheduleUncheckedUpdateManyWithoutTripNestedInput
}

export type TripCreateManyOperatorInput = {
  id?: string
  vesselId: string
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TripUpdateWithoutOperatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vessel?: Prisma.VesselUpdateOneRequiredWithoutTripsNestedInput
  schedules?: Prisma.TripScheduleUpdateManyWithoutTripNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutOperatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vesselId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  schedules?: Prisma.TripScheduleUncheckedUpdateManyWithoutTripNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateManyWithoutOperatorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vesselId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TripCreateManyVesselInput = {
  id?: string
  operatorId?: string | null
  title: string
  description?: string | null
  category?: string | null
  externalReference?: string | null
  durationMinutes?: number | null
  isRecurring?: boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: string | null
  arrivalPort?: string | null
  routeName?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type TripUpdateWithoutVesselInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  operator?: Prisma.OperatorUpdateOneWithoutTripsNestedInput
  schedules?: Prisma.TripScheduleUpdateManyWithoutTripNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateWithoutVesselInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  schedules?: Prisma.TripScheduleUncheckedUpdateManyWithoutTripNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutTripNestedInput
}

export type TripUncheckedUpdateManyWithoutVesselInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operatorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  externalReference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isRecurring?: Prisma.BoolFieldUpdateOperationsInput | boolean
  amenities?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  highlights?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  departurePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  arrivalPort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  routeName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type TripCountOutputType
 */

export type TripCountOutputType = {
  schedules: number
  reviews: number
}

export type TripCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  schedules?: boolean | TripCountOutputTypeCountSchedulesArgs
  reviews?: boolean | TripCountOutputTypeCountReviewsArgs
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripCountOutputType
   */
  select?: Prisma.TripCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeCountSchedulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TripScheduleWhereInput
}

/**
 * TripCountOutputType without action
 */
export type TripCountOutputTypeCountReviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewWhereInput
}


export type TripSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vesselId?: boolean
  operatorId?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  externalReference?: boolean
  durationMinutes?: boolean
  isRecurring?: boolean
  amenities?: boolean
  highlights?: boolean
  departurePort?: boolean
  arrivalPort?: boolean
  routeName?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  vessel?: boolean | Prisma.VesselDefaultArgs<ExtArgs>
  operator?: boolean | Prisma.Trip$operatorArgs<ExtArgs>
  schedules?: boolean | Prisma.Trip$schedulesArgs<ExtArgs>
  reviews?: boolean | Prisma.Trip$reviewsArgs<ExtArgs>
  _count?: boolean | Prisma.TripCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trip"]>

export type TripSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vesselId?: boolean
  operatorId?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  externalReference?: boolean
  durationMinutes?: boolean
  isRecurring?: boolean
  amenities?: boolean
  highlights?: boolean
  departurePort?: boolean
  arrivalPort?: boolean
  routeName?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  vessel?: boolean | Prisma.VesselDefaultArgs<ExtArgs>
  operator?: boolean | Prisma.Trip$operatorArgs<ExtArgs>
}, ExtArgs["result"]["trip"]>

export type TripSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vesselId?: boolean
  operatorId?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  externalReference?: boolean
  durationMinutes?: boolean
  isRecurring?: boolean
  amenities?: boolean
  highlights?: boolean
  departurePort?: boolean
  arrivalPort?: boolean
  routeName?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  vessel?: boolean | Prisma.VesselDefaultArgs<ExtArgs>
  operator?: boolean | Prisma.Trip$operatorArgs<ExtArgs>
}, ExtArgs["result"]["trip"]>

export type TripSelectScalar = {
  id?: boolean
  vesselId?: boolean
  operatorId?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  externalReference?: boolean
  durationMinutes?: boolean
  isRecurring?: boolean
  amenities?: boolean
  highlights?: boolean
  departurePort?: boolean
  arrivalPort?: boolean
  routeName?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type TripOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "vesselId" | "operatorId" | "title" | "description" | "category" | "externalReference" | "durationMinutes" | "isRecurring" | "amenities" | "highlights" | "departurePort" | "arrivalPort" | "routeName" | "isActive" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["trip"]>
export type TripInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vessel?: boolean | Prisma.VesselDefaultArgs<ExtArgs>
  operator?: boolean | Prisma.Trip$operatorArgs<ExtArgs>
  schedules?: boolean | Prisma.Trip$schedulesArgs<ExtArgs>
  reviews?: boolean | Prisma.Trip$reviewsArgs<ExtArgs>
  _count?: boolean | Prisma.TripCountOutputTypeDefaultArgs<ExtArgs>
}
export type TripIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vessel?: boolean | Prisma.VesselDefaultArgs<ExtArgs>
  operator?: boolean | Prisma.Trip$operatorArgs<ExtArgs>
}
export type TripIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vessel?: boolean | Prisma.VesselDefaultArgs<ExtArgs>
  operator?: boolean | Prisma.Trip$operatorArgs<ExtArgs>
}

export type $TripPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Trip"
  objects: {
    vessel: Prisma.$VesselPayload<ExtArgs>
    operator: Prisma.$OperatorPayload<ExtArgs> | null
    schedules: Prisma.$TripSchedulePayload<ExtArgs>[]
    reviews: Prisma.$ReviewPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    vesselId: string
    operatorId: string | null
    title: string
    description: string | null
    category: string | null
    externalReference: string | null
    durationMinutes: number | null
    isRecurring: boolean
    amenities: runtime.JsonValue | null
    highlights: runtime.JsonValue | null
    departurePort: string | null
    arrivalPort: string | null
    routeName: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["trip"]>
  composites: {}
}

export type TripGetPayload<S extends boolean | null | undefined | TripDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TripPayload, S>

export type TripCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TripFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TripCountAggregateInputType | true
  }

export interface TripDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Trip'], meta: { name: 'Trip' } }
  /**
   * Find zero or one Trip that matches the filter.
   * @param {TripFindUniqueArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TripFindUniqueArgs>(args: Prisma.SelectSubset<T, TripFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Trip that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TripFindUniqueOrThrowArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TripFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TripFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Trip that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripFindFirstArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TripFindFirstArgs>(args?: Prisma.SelectSubset<T, TripFindFirstArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Trip that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripFindFirstOrThrowArgs} args - Arguments to find a Trip
   * @example
   * // Get one Trip
   * const trip = await prisma.trip.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TripFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TripFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Trips that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Trips
   * const trips = await prisma.trip.findMany()
   * 
   * // Get first 10 Trips
   * const trips = await prisma.trip.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tripWithIdOnly = await prisma.trip.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TripFindManyArgs>(args?: Prisma.SelectSubset<T, TripFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Trip.
   * @param {TripCreateArgs} args - Arguments to create a Trip.
   * @example
   * // Create one Trip
   * const Trip = await prisma.trip.create({
   *   data: {
   *     // ... data to create a Trip
   *   }
   * })
   * 
   */
  create<T extends TripCreateArgs>(args: Prisma.SelectSubset<T, TripCreateArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Trips.
   * @param {TripCreateManyArgs} args - Arguments to create many Trips.
   * @example
   * // Create many Trips
   * const trip = await prisma.trip.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TripCreateManyArgs>(args?: Prisma.SelectSubset<T, TripCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Trips and returns the data saved in the database.
   * @param {TripCreateManyAndReturnArgs} args - Arguments to create many Trips.
   * @example
   * // Create many Trips
   * const trip = await prisma.trip.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Trips and only return the `id`
   * const tripWithIdOnly = await prisma.trip.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TripCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TripCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Trip.
   * @param {TripDeleteArgs} args - Arguments to delete one Trip.
   * @example
   * // Delete one Trip
   * const Trip = await prisma.trip.delete({
   *   where: {
   *     // ... filter to delete one Trip
   *   }
   * })
   * 
   */
  delete<T extends TripDeleteArgs>(args: Prisma.SelectSubset<T, TripDeleteArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Trip.
   * @param {TripUpdateArgs} args - Arguments to update one Trip.
   * @example
   * // Update one Trip
   * const trip = await prisma.trip.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TripUpdateArgs>(args: Prisma.SelectSubset<T, TripUpdateArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Trips.
   * @param {TripDeleteManyArgs} args - Arguments to filter Trips to delete.
   * @example
   * // Delete a few Trips
   * const { count } = await prisma.trip.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TripDeleteManyArgs>(args?: Prisma.SelectSubset<T, TripDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Trips.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Trips
   * const trip = await prisma.trip.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TripUpdateManyArgs>(args: Prisma.SelectSubset<T, TripUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Trips and returns the data updated in the database.
   * @param {TripUpdateManyAndReturnArgs} args - Arguments to update many Trips.
   * @example
   * // Update many Trips
   * const trip = await prisma.trip.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Trips and only return the `id`
   * const tripWithIdOnly = await prisma.trip.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TripUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TripUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Trip.
   * @param {TripUpsertArgs} args - Arguments to update or create a Trip.
   * @example
   * // Update or create a Trip
   * const trip = await prisma.trip.upsert({
   *   create: {
   *     // ... data to create a Trip
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Trip we want to update
   *   }
   * })
   */
  upsert<T extends TripUpsertArgs>(args: Prisma.SelectSubset<T, TripUpsertArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Trips.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripCountArgs} args - Arguments to filter Trips to count.
   * @example
   * // Count the number of Trips
   * const count = await prisma.trip.count({
   *   where: {
   *     // ... the filter for the Trips we want to count
   *   }
   * })
  **/
  count<T extends TripCountArgs>(
    args?: Prisma.Subset<T, TripCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TripCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Trip.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TripAggregateArgs>(args: Prisma.Subset<T, TripAggregateArgs>): Prisma.PrismaPromise<GetTripAggregateType<T>>

  /**
   * Group by Trip.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TripGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TripGroupByArgs['orderBy'] }
      : { orderBy?: TripGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TripGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTripGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Trip model
 */
readonly fields: TripFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Trip.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TripClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  vessel<T extends Prisma.VesselDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VesselDefaultArgs<ExtArgs>>): Prisma.Prisma__VesselClient<runtime.Types.Result.GetResult<Prisma.$VesselPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  operator<T extends Prisma.Trip$operatorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$operatorArgs<ExtArgs>>): Prisma.Prisma__OperatorClient<runtime.Types.Result.GetResult<Prisma.$OperatorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  schedules<T extends Prisma.Trip$schedulesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$schedulesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripSchedulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reviews<T extends Prisma.Trip$reviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Trip$reviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Trip model
 */
export interface TripFieldRefs {
  readonly id: Prisma.FieldRef<"Trip", 'String'>
  readonly vesselId: Prisma.FieldRef<"Trip", 'String'>
  readonly operatorId: Prisma.FieldRef<"Trip", 'String'>
  readonly title: Prisma.FieldRef<"Trip", 'String'>
  readonly description: Prisma.FieldRef<"Trip", 'String'>
  readonly category: Prisma.FieldRef<"Trip", 'String'>
  readonly externalReference: Prisma.FieldRef<"Trip", 'String'>
  readonly durationMinutes: Prisma.FieldRef<"Trip", 'Int'>
  readonly isRecurring: Prisma.FieldRef<"Trip", 'Boolean'>
  readonly amenities: Prisma.FieldRef<"Trip", 'Json'>
  readonly highlights: Prisma.FieldRef<"Trip", 'Json'>
  readonly departurePort: Prisma.FieldRef<"Trip", 'String'>
  readonly arrivalPort: Prisma.FieldRef<"Trip", 'String'>
  readonly routeName: Prisma.FieldRef<"Trip", 'String'>
  readonly isActive: Prisma.FieldRef<"Trip", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Trip", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Trip", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Trip", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Trip findUnique
 */
export type TripFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip findUniqueOrThrow
 */
export type TripFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip findFirst
 */
export type TripFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Trips.
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Trips.
   */
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Trip findFirstOrThrow
 */
export type TripFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trip to fetch.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Trips.
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Trips.
   */
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Trip findMany
 */
export type TripFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter, which Trips to fetch.
   */
  where?: Prisma.TripWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Trips to fetch.
   */
  orderBy?: Prisma.TripOrderByWithRelationInput | Prisma.TripOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Trips.
   */
  cursor?: Prisma.TripWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Trips from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Trips.
   */
  skip?: number
  distinct?: Prisma.TripScalarFieldEnum | Prisma.TripScalarFieldEnum[]
}

/**
 * Trip create
 */
export type TripCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * The data needed to create a Trip.
   */
  data: Prisma.XOR<Prisma.TripCreateInput, Prisma.TripUncheckedCreateInput>
}

/**
 * Trip createMany
 */
export type TripCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Trips.
   */
  data: Prisma.TripCreateManyInput | Prisma.TripCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Trip createManyAndReturn
 */
export type TripCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * The data used to create many Trips.
   */
  data: Prisma.TripCreateManyInput | Prisma.TripCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Trip update
 */
export type TripUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * The data needed to update a Trip.
   */
  data: Prisma.XOR<Prisma.TripUpdateInput, Prisma.TripUncheckedUpdateInput>
  /**
   * Choose, which Trip to update.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip updateMany
 */
export type TripUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Trips.
   */
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyInput>
  /**
   * Filter which Trips to update
   */
  where?: Prisma.TripWhereInput
  /**
   * Limit how many Trips to update.
   */
  limit?: number
}

/**
 * Trip updateManyAndReturn
 */
export type TripUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * The data used to update Trips.
   */
  data: Prisma.XOR<Prisma.TripUpdateManyMutationInput, Prisma.TripUncheckedUpdateManyInput>
  /**
   * Filter which Trips to update
   */
  where?: Prisma.TripWhereInput
  /**
   * Limit how many Trips to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Trip upsert
 */
export type TripUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * The filter to search for the Trip to update in case it exists.
   */
  where: Prisma.TripWhereUniqueInput
  /**
   * In case the Trip found by the `where` argument doesn't exist, create a new Trip with this data.
   */
  create: Prisma.XOR<Prisma.TripCreateInput, Prisma.TripUncheckedCreateInput>
  /**
   * In case the Trip was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TripUpdateInput, Prisma.TripUncheckedUpdateInput>
}

/**
 * Trip delete
 */
export type TripDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
  /**
   * Filter which Trip to delete.
   */
  where: Prisma.TripWhereUniqueInput
}

/**
 * Trip deleteMany
 */
export type TripDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Trips to delete
   */
  where?: Prisma.TripWhereInput
  /**
   * Limit how many Trips to delete.
   */
  limit?: number
}

/**
 * Trip.operator
 */
export type Trip$operatorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Operator
   */
  select?: Prisma.OperatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Operator
   */
  omit?: Prisma.OperatorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OperatorInclude<ExtArgs> | null
  where?: Prisma.OperatorWhereInput
}

/**
 * Trip.schedules
 */
export type Trip$schedulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripSchedule
   */
  select?: Prisma.TripScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripSchedule
   */
  omit?: Prisma.TripScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripScheduleInclude<ExtArgs> | null
  where?: Prisma.TripScheduleWhereInput
  orderBy?: Prisma.TripScheduleOrderByWithRelationInput | Prisma.TripScheduleOrderByWithRelationInput[]
  cursor?: Prisma.TripScheduleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TripScheduleScalarFieldEnum | Prisma.TripScheduleScalarFieldEnum[]
}

/**
 * Trip.reviews
 */
export type Trip$reviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Review
   */
  select?: Prisma.ReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Review
   */
  omit?: Prisma.ReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewInclude<ExtArgs> | null
  where?: Prisma.ReviewWhereInput
  orderBy?: Prisma.ReviewOrderByWithRelationInput | Prisma.ReviewOrderByWithRelationInput[]
  cursor?: Prisma.ReviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * Trip without action
 */
export type TripDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Trip
   */
  select?: Prisma.TripSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Trip
   */
  omit?: Prisma.TripOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripInclude<ExtArgs> | null
}
